export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ONE_TRANSACTION = "GET_ONE_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";
export const LOAD_ME = "LOAD_ME";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";

export const GET_ALL_GOODS = "GET_ALL_GOODS";
export const GOOD_ERROR = "GOOD_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
